# Generated by Django 4.0.6 on 2022-08-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_category_url_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(unique=True, verbose_name='category_url'),
        ),
    ]
