# Generated by Django 4.0.6 on 2022-08-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_category_name_alter_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(unique=True, verbose_name='Ссылка'),
        ),
    ]
